"""Add distance ETA and completed_at to deployment models

Revision ID: 2de6a210b725
Revises: bdaeda6a7f28
Create Date: 2026-08-17 12:47:58.549822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de6a210b725'
down_revision: Union[str, Sequence[str], None] = 'bdaeda6a7f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recommendations', sa.Column('estimated_distance', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('estimated_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'estimated_time')
    op.drop_column('recommendations', 'estimated_distance')
    op.drop_column('deployments', 'completed_at')
    # ### end Alembic commands ###
