"""Initial Phase 3 schema migration

Revision ID: e9b3c521bc13
Revises: 
Create Date: 2026-08-17 12:17:32.547748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9b3c521bc13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('junctions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_junctions_id'), 'junctions', ['id'], unique=False)
    op.create_index(op.f('ix_junctions_name'), 'junctions', ['name'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('junction_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction', sa.String(length=255), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=True),
    sa.Column('features_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['junction_id'], ['junctions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_junction_id'), 'predictions', ['junction_id'], unique=False)
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    op.create_table('traffic_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('junction_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('traffic_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['junction_id'], ['junctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_observations_id'), 'traffic_observations', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_observations_junction_id'), 'traffic_observations', ['junction_id'], unique=False)
    op.create_index(op.f('ix_traffic_observations_timestamp'), 'traffic_observations', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_observations_timestamp'), table_name='traffic_observations')
    op.drop_index(op.f('ix_traffic_observations_junction_id'), table_name='traffic_observations')
    op.drop_index(op.f('ix_traffic_observations_id'), table_name='traffic_observations')
    op.drop_table('traffic_observations')
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_junction_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_junctions_name'), table_name='junctions')
    op.drop_index(op.f('ix_junctions_id'), table_name='junctions')
    op.drop_table('junctions')
    # ### end Alembic commands ###
