from datetime import datetime
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field, ConfigDict


# ----------------------------------------------------
# 1. Locations Schemas
# ----------------------------------------------------
class LocationItem(BaseModel):
    id: str = Field(..., description="Unique location identifier")
    name: str = Field(..., description="Location/junction name")
    latitude: float = Field(..., description="Latitude coordinate")
    longitude: float = Field(..., description="Longitude coordinate")
    address: Optional[str] = Field(None, description="Location address")

    model_config = ConfigDict(from_attributes=True)


class LocationListResponse(BaseModel):
    locations: List[LocationItem] = Field(..., description="List of monitored locations")


# ----------------------------------------------------
# 2. Traffic Schemas
# ----------------------------------------------------
class TrafficItem(BaseModel):
    id: str = Field(..., description="Traffic observation record ID")
    locationId: str = Field(..., description="Associated location ID")
    timestamp: datetime = Field(..., description="Observation timestamp")
    speed: Optional[float] = Field(None, description="Average speed in km/h")
    density: Optional[float] = Field(None, description="Traffic density count")
    congestionLevel: str = Field("MODERATE", description="Congestion category: LOW, MODERATE, HIGH, SEVERE")
    details: Dict[str, Any] = Field(default_factory=dict, description="Raw feature details")


class TrafficListResponse(BaseModel):
    traffic: List[TrafficItem] = Field(..., description="Current traffic observations across locations")


# ----------------------------------------------------
# 3. Incident Schemas
# ----------------------------------------------------
class IncidentItem(BaseModel):
    id: str = Field(..., description="Incident ID")
    locationId: str = Field(..., description="Location ID")
    locationName: Optional[str] = Field(None, description="Name of the junction/location")
    timestamp: datetime = Field(..., description="Incident timestamp")
    type: str = Field(..., description="Incident type e.g. ACCIDENT, CONGESTION, HAZARD")
    severity: str = Field(..., description="Severity level: LOW, MEDIUM, HIGH, CRITICAL")
    status: str = Field(..., description="Status: ACTIVE, RESOLVED, IN_PROGRESS")
    description: Optional[str] = Field(None, description="Description or details")
    isSimulated: bool = Field(False, description="True if generated by incident simulator")

    model_config = ConfigDict(from_attributes=True)


class IncidentListResponse(BaseModel):
    incidents: List[IncidentItem] = Field(..., description="List of active/recent incidents")


class IncidentSimulateRequest(BaseModel):
    locationId: str = Field(..., description="Target location ID")
    type: str = Field("ACCIDENT", description="Incident type")
    severity: str = Field("HIGH", description="Severity level")
    description: Optional[str] = Field(None, description="Simulated incident details")


# ----------------------------------------------------
# 4. Police Unit Schemas
# ----------------------------------------------------
class PoliceUnitItem(BaseModel):
    id: str = Field(..., description="Police unit ID")
    name: str = Field(..., description="Unit name")
    badgeNumber: Optional[str] = Field(None, description="Badge or vehicle number")
    unitType: str = Field("PATROL", description="Unit type: PATROL, TRAFFIC, RESPONSE")
    status: str = Field("AVAILABLE", description="Status: AVAILABLE, DEPLOYED, UNAVAILABLE")
    zone: Optional[str] = Field(None, description="Operational Zone (CENTRAL, NORTH, EAST, WEST, SOUTH)")
    zone_code: Optional[str] = Field(None, description="Zone code")
    latitude: float = Field(..., description="Unit current latitude")
    longitude: float = Field(..., description="Unit current longitude")
    updatedAt: datetime = Field(..., description="Last location update timestamp")

    model_config = ConfigDict(from_attributes=True)


class PoliceUnitListResponse(BaseModel):
    units: List[PoliceUnitItem] = Field(..., description="List of police units")


# ----------------------------------------------------
# 5. Routing Schemas
# ----------------------------------------------------
class RoutingPoint(BaseModel):
    latitude: float
    longitude: float


class GeoJSONGeometry(BaseModel):
    type: str = Field("LineString", description="GeoJSON type")
    coordinates: List[List[float]] = Field(..., description="List of [longitude, latitude] coordinate pairs")


class RoutingResponse(BaseModel):
    unitId: str = Field(..., description="ID of dispatched police unit")
    junctionId: str = Field(..., description="Destination location ID")
    distanceMeters: int = Field(..., description="Calculated route distance in meters")
    distanceKm: float = Field(..., description="Calculated route distance in km")
    estimatedTimeSeconds: int = Field(..., description="Estimated travel time in seconds")
    estimatedTimeMinutes: float = Field(..., description="Estimated travel time in minutes")
    routeGeometry: GeoJSONGeometry = Field(..., description="GeoJSON LineString route geometry")
    route: Optional[List[RoutingPoint]] = Field(None, description="Waypoints list for map polyline compatibility")
    isSimulated: bool = Field(False, description="True if fallback spatial calculation was used")


# ----------------------------------------------------
# 6. Coverage Schemas
# ----------------------------------------------------
class CoverageItem(BaseModel):
    locationId: str = Field(..., description="Location ID")
    locationName: str = Field(..., description="Location Name")
    activeUnitsCount: int = Field(0, description="Count of units currently nearby/assigned")
    coveragePercentage: float = Field(..., description="Calculated coverage percentage (0-100%)")
    status: str = Field("ADEQUATE", description="Status: ADEQUATE, LOW, CRITICAL")


class CoverageResponse(BaseModel):
    overallCoveragePercentage: float = Field(..., description="City-wide average coverage score")
    totalActiveUnits: int = Field(..., description="Total active police units")
    locations: List[CoverageItem] = Field(..., description="Location coverage breakdown")


class LocationCoverageResponse(BaseModel):
    coverage: CoverageItem = Field(..., description="Coverage metrics for specific location")


# ----------------------------------------------------
# 7. Risk Schemas
# ----------------------------------------------------
class RiskItem(BaseModel):
    locationId: str = Field(..., description="Location ID")
    locationName: str = Field(..., description="Location Name")
    riskLevel: str = Field(..., description="Calculated risk level e.g. LOW, MODERATE, HIGH, SEVERE")
    riskScore: Optional[float] = Field(None, description="Risk score or model prediction value")
    prediction: Union[int, float, str, Any] = Field(..., description="Raw model prediction")
    isMock: Optional[bool] = Field(None, description="True if dev mock adapter was used")
    lastEvaluated: datetime = Field(..., description="Timestamp of risk assessment")


class RiskResponse(BaseModel):
    riskData: List[RiskItem] = Field(..., description="Risk predictions for monitored locations")


class LocationRiskResponse(BaseModel):
    risk: RiskItem = Field(..., description="Risk assessment for specific location")


# ----------------------------------------------------
# 8. Recommendation Schemas
# ----------------------------------------------------
class RecommendationItem(BaseModel):
    id: str = Field(..., description="Recommendation ID")
    locationId: str = Field(..., description="Target location ID")
    locationName: Optional[str] = Field(None, description="Location Name")
    recommendedUnitId: Optional[str] = Field(None, description="Recommended police unit ID")
    unitName: Optional[str] = Field(None, description="Police unit name")
    reason: str = Field(..., description="Reason for deployment recommendation")
    priority: str = Field("MEDIUM", description="Priority: LOW, MEDIUM, HIGH, CRITICAL")
    estimatedDistance: Optional[float] = Field(None, description="Estimated distance in km")
    estimatedTime: Optional[float] = Field(None, description="Estimated travel time in minutes")
    status: str = Field("PENDING", description="Status: PENDING, ACCEPTED, REJECTED")
    timestamp: datetime = Field(..., description="Recommendation creation timestamp")

    model_config = ConfigDict(from_attributes=True)


class RecommendationListResponse(BaseModel):
    recommendations: List[RecommendationItem] = Field(..., description="List of deployment recommendations")


class RecommendationUpdateRequest(BaseModel):
    priority: Optional[str] = Field(None, description="Update priority: LOW, MEDIUM, HIGH, CRITICAL")
    reason: Optional[str] = Field(None, description="Update reason text")
    recommendedUnitId: Optional[str] = Field(None, description="Reassign unit ID")


# ----------------------------------------------------
# 9. Deployment Schemas
# ----------------------------------------------------
class DeploymentItem(BaseModel):
    id: str = Field(..., description="Deployment ID")
    unitId: str = Field(..., description="Deployed unit ID")
    unitName: Optional[str] = Field(None, description="Deployed unit name")
    locationId: str = Field(..., description="Deployed location ID")
    locationName: Optional[str] = Field(None, description="Location name")
    recommendationId: Optional[str] = Field(None, description="Source recommendation ID")
    status: str = Field("ACTIVE", description="Status: ACTIVE, COMPLETED")
    deployedAt: datetime = Field(..., description="Deployment timestamp")

    model_config = ConfigDict(from_attributes=True)


class DeploymentListResponse(BaseModel):
    deployments: List[DeploymentItem] = Field(..., description="List of active police deployments")


class AcceptRecommendationResponse(BaseModel):
    success: bool = True
    deployment: DeploymentItem
    recommendation: RecommendationItem


class RejectRecommendationResponse(BaseModel):
    success: bool = True
    recommendation: RecommendationItem


class IncidentSimulateResponse(BaseModel):
    incident: IncidentItem
    recommendation: Optional[RecommendationItem] = None
